# Generated by Django 5.2.13 on 2026-04-13 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id_agencia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': 'Agências',
                'db_table': 'agencia',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id_distrito', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'db_table': 'distrito',
            },
        ),
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id_proprietario', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Proprietário',
                'verbose_name_plural': 'Proprietários',
                'db_table': 'proprietario',
            },
        ),
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id_rede', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Rede',
                'verbose_name_plural': 'Redes',
                'db_table': 'rede',
            },
        ),
        migrations.CreateModel(
            name='Consultor',
            fields=[
                ('id_consultor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('id_agencia', models.ForeignKey(blank=True, db_column='id_agencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.agencia')),
            ],
            options={
                'verbose_name': 'Consultor',
                'verbose_name_plural': 'Consultores',
                'db_table': 'consultor',
            },
        ),
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id_anunciante', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.IntegerField(choices=[(1, 'Proprietário'), (2, 'Consultor'), (3, 'Agência')])),
                ('id_agencia', models.ForeignKey(blank=True, db_column='id_agencia', null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.agencia')),
                ('id_consultor', models.ForeignKey(blank=True, db_column='id_consultor', null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.consultor')),
                ('id_proprietario', models.ForeignKey(blank=True, db_column='id_proprietario', null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.proprietario')),
            ],
            options={
                'verbose_name': 'Anunciante',
                'verbose_name_plural': 'Anunciantes',
                'db_table': 'anunciante',
            },
        ),
        migrations.CreateModel(
            name='Concelho',
            fields=[
                ('id_concelho', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('id_distrito', models.ForeignKey(blank=True, db_column='id_distrito', null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.distrito')),
            ],
            options={
                'verbose_name': 'Concelho',
                'verbose_name_plural': 'Concelhos',
                'db_table': 'concelho',
            },
        ),
        migrations.CreateModel(
            name='Freguesia',
            fields=[
                ('id_freguesia', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_freguesia', models.CharField(blank=True, max_length=9, null=True)),
                ('nome', models.CharField(max_length=255)),
                ('id_concelho', models.ForeignKey(blank=True, db_column='id_concelho', null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.concelho')),
            ],
            options={
                'verbose_name': 'Freguesia',
                'verbose_name_plural': 'Freguesias',
                'db_table': 'freguesia',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id_imovel', models.AutoField(primary_key=True, serialize=False)),
                ('morada', models.CharField(max_length=255)),
                ('data_anuncio', models.DateTimeField(auto_now_add=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero_quartos', models.PositiveIntegerField(default=0)),
                ('numero_wc', models.PositiveIntegerField(default=0)),
                ('data_construcao', models.DateField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_anunciante', models.ForeignKey(db_column='id_anunciante', on_delete=django.db.models.deletion.CASCADE, to='imovel.anunciante')),
                ('id_freguesia', models.ForeignKey(db_column='id_freguesia', on_delete=django.db.models.deletion.CASCADE, to='imovel.freguesia')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
                'db_table': 'imovel',
                'ordering': ['-data_anuncio'],
            },
        ),
        migrations.AddField(
            model_name='agencia',
            name='id_rede',
            field=models.ForeignKey(blank=True, db_column='id_rede', null=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.rede'),
        ),
    ]
