# Generated by Django 5.2.13 on 2026-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0002_perfilutilizador'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='imagem_principal',
            field=models.ImageField(blank=True, null=True, upload_to='imoveis/'),
        ),
    ]
